### ISSUE TITLE
JOSS review: edits to paper.md

### ISSUE THREAD

**Issue by nirum** [andim/noisyopt#10]
A few suggested edits in the `paper.md` file:

- [x] First sentence of the second paragraph, change "for generic optimization problem" to "for generic optimization problems"
- [x] "taylored" should be "tailored"
- [x] Are the references missing for adaptive pattern search and SPSA?
- [x] Add text mentioning that this is for zeroth-order (gradient free) optimization (issue #8)

**Comment by andim** [comment]
Thanks for catching the typos and thanks for your clarification question. I have updated the paper accordingly -- let me know what you think!

**Comment by nirum** [comment]
Looks good!
