### ISSUE TITLE
Allow parallel function calls

### ISSUE THREAD

**Issue by thomasahle** [andim/noisyopt#12]
Is there a way to run the objective function in parallel?
Ideally something like the "ask and tell" interface to skopt: https://scikit-optimize.github.io/auto_examples/ask-and-tell.html

**Comment by andim** [comment]
Adding some functionality of this sort sounds like a great idea! Would be happy to accept a pull-request implementing such an interface. Unfortunately currently this is not implemented.

**Comment by microprediction** [comment]
Would this pattern work?  No change to the optimization code required. 
https://github.com/microprediction/humpday/blob/main/Embarrassingly_SHGO.ipynb
