### ISSUE TITLE
Example that I can't make work

### ISSUE THREAD

**Issue by microprediction** [andim/noisyopt#14]
Simple 1-d noisy function fails to optimize

https://gist.github.com/microprediction/fe8aa1705595de25c836290cc7afe64f

**Comment by vishalmhjn** [comment]
AFAIK, SPSA may need some tinkering with the default parameter, for It to work right

**Comment by andim** [comment]
Please excuse my slow reply, I had missed your comment!

Indeed this is a problem with the parameter choice. In particular the step size needs to be scaled down. The initial step size is controlled by the parameter `a`. Setting it to a small value, e.g. 1e-3 leads to a correct minimization.

https://gist.github.com/andim/474d4c8203f0b26c988eff878a822405
