### ISSUE TITLE
JOSS review: installing dependencies via pip

### ISSUE THREAD

**Issue by nirum** [andim/noisyopt#4]
Hi,

I'm trying to install `noisyopt` in a clean conda environment running python 3.5. Running `pip install noisyopt` does not install the dependencies (numpy, scipy). I see that you do include a `requires` keyword argument in your `setup.py` file, does this need to be `install_requires`? (as in https://packaging.python.org/requirements/).

Also, not necessary if you don't want to, but I think it would be good to include a list of dependences somewhere in the README.

**Comment by nirum** [comment]
(edit: just noticed the dependencies are listed in the Installation section in the README)

**Comment by andim** [comment]
Thanks for noticing this! Fixed this in 7c0c40ee4d9d229e9514f4e4e33695d409ecfed5

**Comment by nirum** [comment]
Thanks! Mind pushing an update to pypi? you could just bump the version to 0.2.1
