### ISSUE TITLE
JOSS review: error in tutorial

### ISSUE THREAD

**Issue by nirum** [andim/noisyopt#5]
I'm trying to run the tutorial, but get the following error: `TypeError: obj() got an unexpected keyword argument 'seed'`. Should I be setting `paired=False`?

![screen shot 2017-05-11 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/904854/25974291/1aed6dd6-365d-11e7-8b85-c22e687effa1.png)

**Comment by andim** [comment]
Yes, indeed. I have changed the default to be paired, but forgot to change the tutorial accordingly. Fixed in 2949ae216a2ef929043c91f9b4d8622c826ce00b .

Additionally I added the optimization described in the tutorial to a stand-alone python script in a new examples directory.

**Comment by nirum** [comment]
cool, thanks!

**Comment by arthurmath** [comment]
If it still doesn't work, setting minimizeCompass argument paired=False have worked for me.
