### ISSUE TITLE
JOSS review: python version compatibility

### ISSUE THREAD

**Issue by nirum** [andim/noisyopt#6]
I tested `noisyopt` with python 2.7, 3.4, 3.5, and 3.6 and it worked with all of them--is there a reason why the repo badges (and PyPI) only list 2.7 and 3.5 as being compatible versions? Seems to me like you could support 3.4 and 3.6 as well without any extra effort. (especially 3.6, since that is the current version of python)

**Comment by andim** [comment]
2.7 and 3.5 are the versions that I have been testing it for (e.g. on travis ci https://travis-ci.org/andim/noisyopt).

I indeed expect it to work on other python 3 versions. I have added 3.6 to travisCI and will try to update the versions on PyPI accordingly.

**Comment by nirum** [comment]
👍
