### ISSUE TITLE
JOSS review: Tutorial edits

### ISSUE THREAD

**Issue by nirum** [andim/noisyopt#7]
These are minor, but a couple of comments on the tutorial:

- [x] The optimal parameters for the noisy quadratic are (0, 0), but given the restricted bounds, the optimal solution is (0, 0.5). Perhaps just add a note at the bottom of the tutorial emphasizing the fact that noisy opt finds the correct solution of (0, 0.5) ?
- [x] The tutorial only runs the `minimizeCompass` function, but it also works using `minimizeSPSA`--it might be nice to extend the tutorial to minimize the same function using this other method as well, and compare and contrast the two algorithms.

**Comment by andim** [comment]
Thanks for these ideas! They are addressed in 4193cf7c7c6c23904ee2029b48149e7704b115e6 and 29cbe6de99d809bfa73486f1de2f537c7b24f03d .
